name: Scan HTML Output

on:
  push:
    branches:
      - main
      - develop

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required to checkout and read repo files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "template"
          template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
          exit-code: "1"
          ignore-unfixed: true
          scanners: "vuln"
          severity: "HIGH,CRITICAL"
          output: "index.html"

      # This is a custom N8N webhook call to convert the HTML report to PDF 
      # using gotenberg and slack api incoming webhook call
      - name: Convert HTML to PDF via N8N
        if: ${{ !cancelled() }}
        run: |
          curl -X POST "${{ secrets.N8N_WEBHOOK }}" \
          -H "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}" \
          -F 'html=@./index.html' \
          -F "metadata={ \
          \"repo_url\":\"${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}\", \
          \"branch\":\"${{ github.ref_name }}\", \
          \"repo\":\"${{ github.repository }}\" \
          };type=application/json" 